### ISSUE TITLE
NOC examples in Processing fail to dowload

### ISSUE THREAD

**Issue by majoha** [shiffman/The-Nature-of-Code-Examples#101]
As the title. I have emailed Daniel a week or so ago but I haven't heard anything and neither has the issue been resolved.

![unnamed](https://user-images.githubusercontent.com/5595954/42728837-6b11b658-87bc-11e8-8a87-c63842dec20e.png)

**Comment by shiffman** [comment]
this should be working now! Re-open if not!

**Comment by majoha** [comment]
Hi Danial,

I can confirm that your examples files now download.
However, I'm not sure if my issue was related to the fact I was using processing-3.3.7? Since I still can't download them using that version.
I'm now using processing-3.4 and everything is fine.
